#!/bin/bash

if [ $# -lt 1 ]; then
  echo "Usage: $0 <config>"
  exit 1
fi

config=$1

# Adjustable parameters
N=18
cores=648
time=00:05:00

temp=submit$config
echo "#!/bin/bash" > $temp
echo "#SBATCH -A latticgc" >> $temp
echo "#SBATCH -p pbatch" >> $temp
echo "#SBATCH --qos=normal" >> $temp
echo "#SBATCH -N $N" >> $temp
echo "#SBATCH -n $cores" >> $temp
echo "#SBATCH -t $time" >> $temp
echo "#SBATCH -J chck$config" >> $temp
echo "#SBATCH -o out.chck.%j" >> $temp
echo "#SBATCH --mail-user=daschaich@gmail.com" >> $temp
echo "#SBATCH --mail-type=FAIL" >> $temp

# Check that we're not going to break anything
dir=`pwd`
lat=$dir/Configs/config.$config.lime
if [ ! -f $lat ]; then
  echo "ERROR: LATTICE $lat NOT FOUND"
  rm -f $temp
  exit 1
fi

lat=Configs/config.$config.lime
out=Configs/CHCK.$config.lime

# Set up run script for this task
awk -v X=$lat '{sub(/inlatGoesHere/,X);print}' add_checksum.lua > TEMP && mv TEMP chck$config.lua
awk -v X=$out '{sub(/outlatGoesHere/,X);print}' chck$config.lua > TEMP && mv TEMP chck$config.lua
echo "srun -N$node -n$cpus /g/g10/schaich2/bin/qhmc chck$config.lua" >> $temp

sbatch $temp
rm $temp
