#!/bin/bash

if [ $# -lt 2 ]; then
  echo "Usage: $0 <Out/out...> <Out/Sout...>"
  exit 1
fi

in=$1
out=$2

echo "Extracted from $in" > $out
echo `grep stamp $in | tail -n 1` >> $out
echo >> $out
grep Stagg $in >> $out
grep PBP $in >> $out
grep "^pbp" $in >> $out
echo >> $out
echo "RUNNING COMPLETED" >> $out
