#!/bin/bash

if [ $# -lt 1 ]; then
  echo "Usage: $0 <files>"
  exit 1
fi

for var in "$@" ; do
  if [ -f $var ] ; then # Ignore non-file arguments
    echo -ne "$var: "
    grep "Total measurement time: " $var | awk '{print 1*$11, "seconds = ", $11/60, "minutes = ", $11/3600, "hours"}'
  fi
done
