#!/bin/bash

if [ $# != 1 ]; then
  echo "Usage: $0 <config>"
  exit 1
fi

cp -iv $1 Configs/config.0.lime
head -n 3 Configs/config.0.lime > TEMP
vim TEMP
rm -fv TEMP
echo 'echo "Started from '${1##\.\.\/}' (time stamp '
