echo "  <p>Last update: `date`</p>"
echo "  <table width=\"1000px\">"
echo "    <tr>"
echo "      <th width=\"500px\">Unflowed</th>"
echo "      <th width=\"500px\">Wilson-flowed</th>"
echo "    </tr>"
echo "    <tr>"
echo "      <td width=\"500px\"><a href=\"poly_hist.gif\"><img src=\"poly_hist.gif\" width=\"450px\"></a></td>"
echo "      <td width=\"500px\"><a href=\"Wpoly_hist.gif\"><img src=\"Wpoly_hist.gif\" width=\"450px\"></a></td>"
echo "    </tr>"
for i in poly_hist_b*.pdf ; do
  echo "    <tr>"
  echo "      <td width=\"500px\"><a href=\""$i"\"><img src=\""${i/pdf/png}"\" width=\"450px\"></a></td>"
  echo "      <td width=\"500px\"><a href=\"W"$i"\"><img src=\"W"${i/pdf/png}"\" width=\"450px\"></a></td>"
  echo "    </tr>"
done
echo "  </table>"
echo "</body></html>"
