#!/bin/bash

if [ $# -lt 1 ]; then
  echo "Usage: $0 <files>"
  exit 1
fi

for var in "$@" ; do
  if [ -f $var ] ; then # Ignore non-file arguments
    echo -ne "$var: "
    grep "total time: " $var | awk '{print 1*$3, "seconds = ", $3/60, "minutes = ", $3/3600, "hours"}'
  fi
done
