#!/bin/bash

# Keep resubmitting from start to end in sets of per_job
if [ $# -lt 8 ]; then
  echo "Usage: $0 <start> <end> <per_job> <MH> <nsteps> <nsteps2> <ngsteps> <time>"
  exit 1
fi

# Input parameters
first=$1
last=$2
batch=$3
MH=$4
nsteps=$5
nsteps2=$6
ngsteps=$7
time=$8

# Check whether we've correctly set $batch to evenly divide ($last-$first)
iter=0
count=$first
for(( i=$first ; $i<$last ; i+=$batch )); do
  iter=$[$iter + 1]
  count=$[$count + $batch]
done
echo "Will submit $iter jobs and end up at $count MDTU"

# Adjustable parameters
N=12
cores=432
ntraj=10
traj_length=1
skip=10   # !!! Should be a way to figure out skip=ntraj*traj_length

# Parameters fixed by the path
temp=`pwd`
path=${temp##*SU4/}   # Strip everything up to and including "SU4/"
mass=${path##*_m}     # Strip everything up to and including "_m"
temp=${path##*f/}     # Strip everything up to and including "f/"
vol=${temp%%/b*}      # Strip everything after and including "/b"
tag=${temp##*/}       # Strip everything up to and including "/"
temp=${tag%%_*}       # Strip everything after and including first "_"
beta=${temp##b}       # Strip b from front of temp

# Common parameters for all jobs
temp=submit_$tag
echo "#!/bin/bash" > $temp
echo "#SBATCH -A latticgc" >> $temp
echo "#SBATCH -p pbatch" >> $temp
echo "#SBATCH --qos=normal" >> $temp
echo "#SBATCH -N $N" >> $temp
echo "#SBATCH -n $cores" >> $temp
echo "#SBATCH -t $time" >> $temp
echo "#SBATCH -J HMC${vol}_$tag" >> $temp
echo "#SBATCH -o out.HMC.%j" >> $temp
echo "#SBATCH --mail-user=daschaich@gmail.com" >> $temp
echo "#SBATCH --mail-type=ALL" >> $temp

dir=/p/lustre1/schaich2/SU4/$path
cd $dir
echo "cd $dir" >> $temp

# Check that we're not going to break anything,
# either through this job or the subsequent jobs it will submit
lat=$dir/Configs/config.$first.lime
if [ ! -f $lat ]; then
  echo "WARNING: LATTICE $lat NOT FOUND"
  # Allow job to be submitted with warning,
  # so it can accumulate priority while the starting config is generated
fi
for(( i=$first ; $i<$last ; i+=$skip )); do
  out=$dir/Out/out.$i-$next
  lat=$dir/Configs/config.$[$i+$skip].lime
  if [ -f $out ]; then
    echo "ERROR: OUTPUT FILE $out EXISTS, SUBMISSION ABORTED"
    rm -f $temp
    exit 1
  fi
  if [ -f $lat ]; then
    echo "ERROR: LATTICE $lat EXISTS, SUBMISSION ABORTED"
    rm -f $temp
    exit 1
  fi
done

# Diagnostic information
echo "echo '=====================JOB DIAGNOTICS========================'" >> $temp
echo "date" >> $temp
echo "echo -n 'This machine is ';hostname" >> $temp
echo "echo -n 'My jobid is '; echo \$SLURM_JOBID" >> $temp
echo "echo 'My path is:' " >> $temp
echo "echo \$PATH" >> $temp
echo "echo 'My job info:'" >> $temp
echo "squeue -j \$SLURM_JOBID" >> $temp
echo "echo 'Machine info'" >> $temp
echo "sinfo -s" >> $temp

# Write this job's evolution tasks to run in a single job
iter=0
this_sub=$[$first + $batch]
for(( i=$first ; $i<$this_sub ; i+=$skip )); do
  iter=$[$iter + 1]
  next=$[$i + $skip]
  out=$dir/Out/out.$i-$next
  lat=$dir/Configs/config

  # Set up run script for this task
  awk -v X=$mass '{sub("massGoesHere",X);print}' ../template.lua > TEMP && mv TEMP RUN$i.lua
  awk -v X=$beta '{sub(/betaGoesHere/,X);print}' RUN$i.lua > TEMP && mv TEMP RUN$i.lua
  awk -v X=$MH '{sub(/mass2GoesHere/,X);print}' RUN$i.lua > TEMP && mv TEMP RUN$i.lua
  awk -v X=$ntraj '{sub(/ntrajGoesHere/,X);print}' RUN$i.lua > TEMP && mv TEMP RUN$i.lua
  awk -v X=$i '{sub(/trajGoesHere/,X);print}' RUN$i.lua > TEMP && mv TEMP RUN$i.lua
  awk -v X=$nsteps '{sub(/nstepsGoesHere/,X);print}' RUN$i.lua > TEMP && mv TEMP RUN$i.lua
  awk -v X=$nsteps2 '{sub(/nsteps2GoesHere/,X);print}' RUN$i.lua > TEMP && mv TEMP RUN$i.lua
  awk -v X=$ngsteps '{sub(/ngstepsGoesHere/,X);print}' RUN$i.lua > TEMP && mv TEMP RUN$i.lua
  awk -v X=$lat.%i.lime '{sub(/latpatGoesHere/,X);print}' RUN$i.lua > TEMP && mv TEMP RUN$i.lua
  awk -v X=${last}${beta/\./41}${vol%%nt*}$i '{sub(/seedGoesHere/,X);print}' RUN$i.lua > TEMP && mv TEMP RUN$i.lua

  echo "echo \"Job HMC${vol}_$tag.$i started \"\`date\`\" jobid \$SLURM_JOBID\" >> $out" >> $temp
  echo "echo \"=== Running MPI application on $cpus cpus ===\" >> $out" >> $temp
  echo "echo \"srun -N$N -n$cores /g/g10/schaich2/bin/qhmc RUN$i.lua\" >> $out" >> $temp
  echo "srun -N$N -n$cores /g/g10/schaich2/bin/qhmc RUN$i.lua >> $out" >> $temp

  echo "echo \"=== MPI application finished at \"\`date\`\" ===\" >> $out" >> $temp
  echo "" >> $temp
done

# Submit next job, if applicable
# Warned above about possibility of ending up between $last and $last+$batch
if [ $this_sub -lt $last ] ; then
  echo "echo \"./runLLNL $this_sub $last $batch $MH $nsteps $nsteps2 $ngsteps $time\"" >> $temp
  echo "./runLLNL $this_sub $last $batch $MH $nsteps $nsteps2 $ngsteps $time" >> $temp
fi

sbatch $temp
rm -f $temp
echo "Requested $time to save $iter configs ($first--$this_sub by $ntraj)"
