#!/bin/bash

if [ $# -lt 3 ]; then
  echo "Usage: $0 <first> <last> <time>"
  exit 1
fi

# Input parameters
first=$1
last=$2
time=$3

# Adjustable parameters
N=12
cores=432
skip=10

# Parameters fixed by the path
temp=`pwd`
path=${temp##*SU4/}   # Strip everything up to and including "SU4/"
mass=${path##*_m}     # Strip everything up to and including "_m"
temp=${path##*f/}     # Strip everything up to and including "f/"
vol=${temp%%/b*}      # Strip everything after and including "/b"
tag=${temp##*/}       # Strip everything up to and including "/"
temp=${tag%%_*}       # Strip everything after and including first "_"
beta=${temp##b}       # Strip b from front of temp

temp=submit$first
echo "#!/bin/bash" > $temp
echo "#SBATCH -A latticgc" >> $temp
echo "#SBATCH -p pbatch" >> $temp
echo "#SBATCH --qos=normal" >> $temp
echo "#SBATCH -N $N" >> $temp
echo "#SBATCH -n $cores" >> $temp
echo "#SBATCH -t $time" >> $temp
echo "#SBATCH -J spect" >> $temp
echo "#SBATCH -o out.spectrum.%j" >> $temp

# Diagnostic information
echo "echo '=====================JOB DIAGNOTICS========================'" >> $temp
echo "date" >> $temp
echo "echo -n 'This machine is ';hostname" >> $temp
echo "echo -n 'My jobid is '; echo \$SLURM_JOBID" >> $temp
echo "echo 'My path is:' " >> $temp
echo "echo \$PATH" >> $temp
echo "echo 'My job info:'" >> $temp
echo "squeue -j \$SLURM_JOBID" >> $temp
echo "echo 'Machine info'" >> $temp
echo "sinfo -s" >> $temp

echo "echo '=====================JOB STARTING=========================='" >> $temp
for(( i=$first ; $i<=$last ; i+=$skip )); do
  echo -ne "Wflow.$i "
  echo "echo $i" >> $temp
  lat=Configs/config.$i.lime
  out=Out/spectrum.$i
  if [ ! -e $lat ]; then
    echo "Error: lattice not found"
    rm -f $temp
    exit 1
  fi
  if [ -e $out ]; then
    echo "Error: output file $out exists"
    rm -f $temp
    exit 1
  fi

  # Set up run script for this task
  awk -v X=$mass '{sub("massGoesHere",X);print}' ../template_spectrum.lua > TEMP && mv TEMP SPECT$i.lua
  awk -v X=$lat '{sub(/inlatGoesHere/,X);print}' SPECT$i.lua > TEMP && mv TEMP SPECT$i.lua
  awk -v X=${last}${beta/\./41}${vol%%nt*}$i '{sub(/seedGoesHere/,X);print}' SPECT$i.lua > TEMP && mv TEMP SPECT$i.lua

  # Go
  echo "echo \"Job spect${vol}_$tag.$i started \"\`date\`\" jobid \$SLURM_JOBID\" >> $out" >> $temp
  echo "echo \"=== Running MPI application on $cpus cpus ===\" >> $out" >> $temp
  echo "echo \"srun -N$N -n$cores /g/g10/schaich2/bin/qhmc SPECT$i.lua\" >> $out" >> $temp
  echo "srun -N$N -n$cores /g/g10/schaich2/bin/qhmc SPECT$i.lua >> $out" >> $temp
  echo "chmod 660 $out" >> $temp
  echo "echo \"=== MPI application finished at \"\`date\`\" ===\" >> $out" >> $temp
done
echo "echo '========================ALL DONE==========================='" >> $temp

sbatch $temp
rm -f $temp
