#!/bin/bash
# ------------------------------------------------------------------
if [ $# != 0 ]; then
  echo "Usage: $0"
  exit 1
fi

temp=`pwd`
if [[ $temp == *"KS_nHYP_FA"* ]] ; then
  dir=${temp##*FA/}   # Strip everything up to and including "FA/"
  path=/data/lsd/KS_nHYP_FA/$dir
elif [[ $temp == *"SU4"* ]] ; then
  dir=${temp##*SU4/}   # Strip everything up to and including "SU4/"
  path=/data/lsd/SU4/$dir
else
  echo "ERROR: Unrecognized path $temp"
  exit 1
fi
# ------------------------------------------------------------------



# ------------------------------------------------------------------
# Construct list of files in given ensemble, for parse_qhmc.py
rm -f list.txt
for i in $path/Out/out.* ; do
  echo ${i##*.} >> temp    # Strip everything up to and including the last "."
done
sort temp -n | uniq > list.txt
rm -f temp

# Use list of files in given ensemble to extract time series data
rm -f data/*.csv ERRORS MISSING
date=`date`
echo "python /home/schaich/bin/parse_qhmc.py"
python /home/schaich/bin/parse_qhmc.py
chmod 664 data/*.csv
rm -f list.txt            # Done with this

# Replace Web page to update timestamp
date=`date`
rm -f index.html
echo writeLSD $dir "$date"
/home/schaich/bin/writeLSD $dir "$date"
chmod 664 index.html
# ------------------------------------------------------------------
