#!/bin/bash
# ------------------------------------------------------------------
if [ $# != 0 ]; then
  echo "Usage: $0"
  exit 1
fi

temp=`pwd`
if [ -d /data/bsm/nHYP/ ] ; then
  dir=${temp##*nHYP/}   # Strip everything up to and including "nHYP/"
  path=/data/bsm/nHYP/$dir
else
  dir=${temp##*BSM/}    # Strip everything up to and including "BSM/"
  path=/nfs/beowulf03/schaich/BSM/$dir
fi
# ------------------------------------------------------------------



# ------------------------------------------------------------------
# Construct list of files in given ensemble,
rm -f list.txt
for i in $path/out.* ; do
  echo ${i##*.} >> temp    # Strip everything up to and including the last "."
done
sort temp -n | uniq > list.txt
rm -f temp

# Use list of files in given ensemble to extract time series data
rm -f data/*.csv ERRORS MISSING
date=`date`
echo "parse_BSM.pl $path"
if [ -f /home/schaich/bin/parse_BSM.pl ] ; then
  /home/schaich/bin/parse_BSM.pl $path
else
  /nfs/beowulf03/beowulf02/anna2/KSNHYP/FA-ks481216/scripts/parse_BSM.pl $path
fi
chmod 664 data/*.csv
rm -f list.txt            # Done with this

# Replace Web page to update timestamp
date=`date`
rm -f index.html
echo writeBSM $dir "$date"
if [ -f /home/schaich/bin/writeBSM ] ; then
  /home/schaich/bin/writeBSM $dir "$date"
else
  /nfs/beowulf03/beowulf02/anna2/KSNHYP/FA-ks481216/scripts/writeBSM $dir "$date"
fi
chmod 664 index.html
# ------------------------------------------------------------------
