#!/bin/bash
# ------------------------------------------------------------------
if [ $# != 0 ]; then
  echo "Usage: $0"
  exit 1
fi

temp=`pwd`  # Strip everything up to and including "KS_nHYP_FA/"
dir=${temp##*KS_nHYP_FA/}
path=/nfs/beowulf03/beowulf02/anna2/KSNHYP/FA-ks481216/$dir
# ------------------------------------------------------------------



# ------------------------------------------------------------------
# Construct list of files in this ensemble
rm -f list.txt
for i in $path/Out/out.* ; do
  echo ${i##*.} >> temp    # Strip everything up to and including the last "."
done
sort temp -n | uniq > list.txt
rm -f temp

# Use list of files in given ensemble to extract time series data
rm -f data/*.csv ERRORS
date=`date`
echo "parse_CU.pl $path"
~/scripts/parse_CU.pl $path
chmod 664 data/*.csv
rm -f list.txt            # Done with this

# Replace Web page to update timestamp
date=`date`
rm -f index.html
echo writeCU $dir "$date"
~/scripts/writeCU $dir "$date"
chmod 664 index.html

# I like to monitor this
wc -l M*
wc -l E*
echo
# ------------------------------------------------------------------
