#!/bin/bash

if [ ! -d /raid1/backup/schaich/LSD/SU4 ] ; then
  echo "Need to mount /raid1..."
  sudo mount rafa.amtp:/raid1 /raid1
fi

cd ~/LSD/SU4/4f
for i in *nt12/b[0-9]*267 *nt6/b*6 ; do
  if [ -d /raid1/backup/schaich/LSD/SU4/$i/data ] ; then
    echo "$i already done"
    continue
  fi

  echo "Doing $i"
  mkdir /raid1/backup/schaich/LSD/SU4/$i
  mkdir /raid1/backup/schaich/LSD/SU4/$i/data
  touch /raid1/backup/schaich/LSD/SU4/$i/ERRORS
  touch /raid1/backup/schaich/LSD/SU4/$i/MISSING

  cd $i
  rm -f data ERRORS MISSING
  ln -s /raid1/backup/schaich/LSD/SU4/$i/data
  ln -s /raid1/backup/schaich/LSD/SU4/$i/ERRORS
  ln -s /raid1/backup/schaich/LSD/SU4/$i/MISSING
  ls -l
  cd ../..
done

cd ~/LSD/SU4/0f
for i in 8nt4/b*W* ; do
  if [ -d /raid1/backup/schaich/LSD/SU4quenched/$i/data ] ; then
    echo "$i already done"
    continue
  fi

  echo "Doing $i"
  mkdir /raid1/backup/schaich/LSD/SU4quenched/$i
  mkdir /raid1/backup/schaich/LSD/SU4quenched/$i/data
  touch /raid1/backup/schaich/LSD/SU4quenched/$i/ERRORS
  touch /raid1/backup/schaich/LSD/SU4quenched/$i/MISSING

  cd $i
  rm -f data ERRORS MISSING
  ln -s /raid1/backup/schaich/LSD/SU4quenched/$i/data
  ln -s /raid1/backup/schaich/LSD/SU4quenched/$i/ERRORS
  ln -s /raid1/backup/schaich/LSD/SU4quenched/$i/MISSING
  ls -l
  cd ../..
done
