#!/bin/bash

if [ $# -lt 2 ]; then
  echo "Usage: $0 <directory> <date>"
  exit 1
fi

tag=$1
date=$2

# Turn Wilson line scatter plots off/on depending on theory
if [ -d "/raid1/backup/schaich/LSD/KS_nHYP_FA/$tag" ] ; then
  out="/raid1/backup/schaich/LSD/KS_nHYP_FA/$tag/index.html"    # Customized for Liverpool
  scatter=0
elif [ -d "/raid1/backup/schaich/LSD/SU4/$tag" ] ; then
  out="/raid1/backup/schaich/LSD/SU4/$tag/index.html"
  scatter=1
elif [ -d "/raid1/backup/schaich/LSD/SU4quenched/$tag" ] ; then
  out="/raid1/backup/schaich/LSD/SU4quenched/$tag/index.html"
  scatter=1
else
  echo "ERROR: Can't find appropriate $tag directory"
  exit 1
fi
#echo "Writing $out"

echo '<html><head>' > $out
echo '<script type="text/javascript" src="http://bsm.physics.yale.edu/ext/plot-ts/nHYP/dygraph-combined.js"></script>' >> $out
echo '<style type="text/css">' >> $out
echo '  #main{' >> $out
echo '    margin-right:19em;' >> $out
echo '    position:relative;' >> $out
echo '    min-height:0' >> $out
echo '  }' >> $out
echo '  #main h2 {background-color:#f0f0f0}' >> $out

echo '  h1, h2, h3 {margin-bottom:1em}' >> $out
echo '  h2, h3, h4 a, h5 a {padding:3px 10px}' >> $out
echo '  h2, h3, h4, h5 {font-size:1em}' >> $out
echo '</style>' >> $out

echo '<title>'$tag'</title>' >> $out
echo '</head>' >> $out
echo '<body>' >> $out
echo '<div id="main">' >> $out
echo '  <p>Last update: '$date'</p>' >> $out
echo '  <h1><a name="phys"></a>Physical observables</h1>' >> $out
echo '  <hr><br>' >> $out
echo '  <div style="width:880px; height:330px;">' >> $out
echo '    <table>' >> $out
echo '      <tr><th>Plaquette ('$tag')</th><th>Chiral condensate ('$tag')</th></tr>' >> $out
echo '      <tr>' >> $out
echo '        <td style="width:400px; height:300px;">' >> $out
echo '          <div id="plaq"></div>' >> $out
echo '          <script type="text/javascript">' >> $out
echo '            g = new Dygraph(document.getElementById("plaq"),' >> $out   # Where to put graph
echo '                            "data/plaq.csv",' >> $out                   # URL for data series
echo '                            { rollPeriod: 50,' >> $out                  # Options
echo '                              colors: ["blue", "orange", "red"],' >> $out
echo '                              showRoller: true,' >> $out
echo '                              yValueFormatter: function(x) {' >> $out
echo '                                var shift = Math.pow(10, 4)' >> $out
echo '                                return Math.round(x * shift) / shift' >> $out
echo '                              },' >> $out
echo '                            });' >> $out
echo '          </script>' >> $out
echo '        </td>' >> $out
echo '        <td style="width:400px; height:300px;">' >> $out
echo '          <div id="pbp"></div>' >> $out
echo '          <script type="text/javascript">' >> $out
echo '            g = new Dygraph(document.getElementById("pbp"),' >> $out
echo '                            "data/pbp.csv",' >> $out
echo '                            { rollPeriod: 50,' >> $out
echo '                              colors: ["blue", "orange"],' >> $out
echo '                              showRoller: true,' >> $out
echo '                              yValueFormatter: function(x) {' >> $out
echo '                                var shift = Math.pow(10, 6)' >> $out
echo '                                return Math.round(x * shift) / shift' >> $out
echo '                              },' >> $out
echo '                            });' >> $out
echo '          </script>' >> $out
echo '        </td>' >> $out
echo '      </tr>' >> $out
echo '    </table>' >> $out
echo '  </div>' >> $out
echo '  <br><br>' >> $out

if [ $scatter -gt 0 ]; then  # scatter set above depending on directory path
  echo '  <div style="width:880px; height:330px;">' >> $out
  echo '    <table>' >> $out
  echo '      <tr><th>Polyakov loop ('$tag')</th><th>Intentionally left blank</th></tr>' >> $out
  echo '      <tr>' >> $out
  echo '        <td style="width:400px; height:300px;">' >> $out
  echo '          <div id="poly"></div>' >> $out
  echo '          <script type="text/javascript">' >> $out
  echo '            g = new Dygraph(document.getElementById("poly"),' >> $out
  echo '                            "data/poly.csv",' >> $out
  echo '                            { colors: ["blue"],' >> $out
  echo '                              drawPoints: true,' >> $out
  echo '                              strokeWidth: 0,' >> $out
  echo '                              showLabelsOnHighlight: false,' >> $out
  echo '                              valueRange: [-1.01, 1.01],' >> $out
  echo '                              dateWindow: [-1.01, 1.01],' >> $out
  echo '                              xValueFormatter: function(x) {' >> $out
  echo '                                var shift = Math.pow(10, 4)' >> $out
  echo '                                return Math.round(x * shift) / shift' >> $out
  echo '                              },' >> $out
  echo '                              yValueFormatter: function(x) {' >> $out
  echo '                                var shift = Math.pow(10, 4)' >> $out
  echo '                                return Math.round(x * shift) / shift' >> $out
  echo '                              },' >> $out
  echo '                            });' >> $out
  echo '          </script>' >> $out
  echo '        </td>' >> $out
  echo '        <td style="width:400px; height:300px;">' >> $out
if [ 0 -gt 1 ]; then
  echo '          <div id="xpoly"></div>' >> $out
  echo '          <script type="text/javascript">' >> $out
  echo '            g = new Dygraph(document.getElementById("xpoly"),' >> $out
  echo '                            "data/xpoly.csv",' >> $out
  echo '                            { colors: ["blue"],' >> $out
  echo '                              drawPoints: true,' >> $out
  echo '                              strokeWidth: 0,' >> $out
  echo '                              showLabelsOnHighlight: false,' >> $out
  echo '                              valueRange: [-1.01, 1.01],' >> $out
  echo '                              dateWindow: [-1.01, 1.01],' >> $out
  echo '                              xValueFormatter: function(x) {' >> $out
  echo '                                var shift = Math.pow(10, 4)' >> $out
  echo '                                return Math.round(x * shift) / shift' >> $out
  echo '                              },' >> $out
  echo '                              yValueFormatter: function(x) {' >> $out
  echo '                                var shift = Math.pow(10, 4)' >> $out
  echo '                                return Math.round(x * shift) / shift' >> $out
  echo '                              },' >> $out
  echo '                            });' >> $out
  echo '          </script>' >> $out
fi
  echo '        </td>' >> $out
  echo '      </tr>' >> $out
  echo '    </table>' >> $out
  echo '  </div>' >> $out
  echo '  <br><br>' >> $out
fi

echo '  <div style="width:880px; height:330px;">' >> $out
echo '    <table>' >> $out
echo '      <tr><th>Re(Polyakov loop) ('$tag')</th><th>Polyakov loop mod ('$tag')</th></tr>' >> $out
echo '      <tr>' >> $out
echo '        <td style="width:400px; height:300px;">' >> $out
echo '          <div id="poly_r"></div>' >> $out
echo '          <script type="text/javascript">' >> $out
echo '            g = new Dygraph(document.getElementById("poly_r"),' >> $out
echo '                            "data/poly_r.csv",' >> $out
echo '                            { rollPeriod: 50,' >> $out
echo '                              colors: ["blue"],' >> $out
echo '                              showRoller: true,' >> $out
echo '                              yValueFormatter: function(x) {' >> $out
echo '                                var shift = Math.pow(10, 4)' >> $out
echo '                                return Math.round(x * shift) / shift' >> $out
echo '                              },' >> $out
echo '                            });' >> $out
echo '          </script>' >> $out
echo '        </td>' >> $out
echo '        <td style="width:400px; height:300px;">' >> $out
echo '          <div id="poly_mod"></div>' >> $out
echo '          <script type="text/javascript">' >> $out
echo '            g = new Dygraph(document.getElementById("poly_mod"),' >> $out
echo '                            "data/poly_mod.csv",' >> $out
echo '                            { rollPeriod: 50,' >> $out
echo '                              colors: ["blue"],' >> $out
echo '                              showRoller: true,' >> $out
echo '                              yValueFormatter: function(x) {' >> $out
echo '                                var shift = Math.pow(10, 4)' >> $out
echo '                                return Math.round(x * shift) / shift' >> $out
echo '                              },' >> $out
echo '                            });' >> $out
echo '          </script>' >> $out
echo '        </td>' >> $out
echo '      </tr>' >> $out
echo '    </table>' >> $out
echo '  </div>' >> $out
echo '  <br><br>' >> $out

# Only include if we actually have something to show
if [ -f data/plaqB.csv ] ; then
  len=`wc -l data/plaqB.csv | awk '{print $1}'`
else
  len=0
fi
if [ $len -gt 1 ]; then
  echo '  <div style="width:880px; height:330px;">' >> $out
  echo '    <table>' >> $out
  echo '      <tr><th>Re(spatial loop) ('$tag')</th><th>Spatial loop mod ('$tag')</th></tr>' >> $out
  echo '      <tr>' >> $out
  echo '        <td style="width:400px; height:300px;">' >> $out
  echo '          <div id="xpoly_r"></div>' >> $out
  echo '          <script type="text/javascript">' >> $out
  echo '            g = new Dygraph(document.getElementById("xpoly_r"),' >> $out
  echo '                            "data/xpoly_r.csv",' >> $out
  echo '                            { rollPeriod: 50,' >> $out
  echo '                              colors: ["blue"],' >> $out
  echo '                              showRoller: true,' >> $out
  echo '                              yValueFormatter: function(x) {' >> $out
  echo '                                var shift = Math.pow(10, 4)' >> $out
  echo '                                return Math.round(x * shift) / shift' >> $out
  echo '                              },' >> $out
  echo '                            });' >> $out
  echo '          </script>' >> $out
  echo '        </td>' >> $out
  echo '        <td style="width:400px; height:300px;">' >> $out
  echo '          <div id="xpoly_mod"></div>' >> $out
  echo '          <script type="text/javascript">' >> $out
  echo '            g = new Dygraph(document.getElementById("xpoly_mod"),' >> $out
  echo '                            "data/xpoly_mod.csv",' >> $out
  echo '                            { rollPeriod: 50,' >> $out
  echo '                              colors: ["blue"],' >> $out
  echo '                              showRoller: true,' >> $out
  echo '                              yValueFormatter: function(x) {' >> $out
  echo '                                var shift = Math.pow(10, 4)' >> $out
  echo '                                return Math.round(x * shift) / shift' >> $out
  echo '                              },' >> $out
  echo '                            });' >> $out
  echo '          </script>' >> $out
  echo '        </td>' >> $out
  echo '      </tr>' >> $out
  echo '    </table>' >> $out
  echo '  </div>' >> $out
  echo '  <br><br>' >> $out
fi

# Only include if we actually have something to show
if [ -f data/plaq_diff.csv ] ; then
  len=`wc -l data/plaq_diff.csv | awk '{print $1}'`
else
  len=0
fi
if [ $len -gt 1 ]; then
  echo '  <div style="width:880px; height:330px;">' >> $out
  echo '    <table>' >> $out
  echo '      <tr><th>Plaquette difference ('$tag')</th><th>Link difference ('$tag')</th></tr>' >> $out
  echo '      <tr>' >> $out
  echo '        <td style="width:400px; height:300px;">' >> $out
  echo '          <div id="plaq_diff"></div>' >> $out
  echo '          <script type="text/javascript">' >> $out
  echo '            g = new Dygraph(document.getElementById("plaq_diff"),' >> $out
  echo '                            "data/plaq_diff.csv",' >> $out
  echo '                            { rollPeriod: 5,' >> $out
  echo '                              colors: ["blue", "orange", "red", "green", "black"],' >> $out
  echo '                              showRoller: true,' >> $out
  echo '                              yValueFormatter: function(x) {' >> $out
  echo '                                var shift = Math.pow(10, 4)' >> $out
  echo '                                return Math.round(x * shift) / shift' >> $out
  echo '                              },' >> $out
  echo '                            });' >> $out
  echo '          </script>' >> $out
  echo '        </td>' >> $out
  echo '        <td style="width:400px; height:300px;">' >> $out
  echo '          <div id="link_diff"></div>' >> $out
  echo '          <script type="text/javascript">' >> $out
  echo '            g = new Dygraph(document.getElementById("link_diff"),' >> $out
  echo '                            "data/link_diff.csv",' >> $out
  echo '                            { rollPeriod: 5,' >> $out
  echo '                              colors: ["blue", "orange", "red", "green", "black"],' >> $out
  echo '                              showRoller: true,' >> $out
  echo '                              yValueFormatter: function(x) {' >> $out
  echo '                                var shift = Math.pow(10, 4)' >> $out
  echo '                                return Math.round(x * shift) / shift' >> $out
  echo '                              },' >> $out
  echo '                            });' >> $out
  echo '          </script>' >> $out
  echo '        </td>' >> $out
  echo '      </tr>' >> $out
  echo '    </table>' >> $out
  echo '  </div>' >> $out
  echo '  <br><br>' >> $out
fi

# Only include if we actually have something to show
if [ -f data/Wflow.csv ] ; then
  len=`wc -l data/Wflow.csv | awk '{print $1}'`
else
  len=0
fi
if [ $len -gt 1 ]; then
  echo '  <div style="width:880px; height:330px;">' >> $out
  echo '    <table>' >> $out
echo '      <tr><th>Re(WPoly) ('$tag')</th><th>Wilson-flowed Polyakov loop mod ('$tag')</th></tr>' >> $out
  echo '      <tr>' >> $out
  echo '        <td style="width:400px; height:300px;">' >> $out
  echo '          <div id="Wpoly"></div>' >> $out
  echo '          <script type="text/javascript">' >> $out
  echo '            g = new Dygraph(document.getElementById("Wpoly"),' >> $out
  echo '                            "data/Wpoly.csv",' >> $out
  echo '                            { rollPeriod: 5,' >> $out
  echo '                              colors: ["blue", "red", "green", "black"],' >> $out
  echo '                              showRoller: true,' >> $out
  echo '                              yValueFormatter: function(x) {' >> $out
  echo '                                var shift = Math.pow(10, 4)' >> $out
  echo '                                return Math.round(x * shift) / shift' >> $out
  echo '                              },' >> $out
  echo '                            });' >> $out
  echo '          </script>' >> $out
  echo '        </td>' >> $out
  echo '        <td style="width:400px; height:300px;">' >> $out
  echo '          <div id="Wpoly_mod"></div>' >> $out
  echo '          <script type="text/javascript">' >> $out
  echo '            g = new Dygraph(document.getElementById("Wpoly_mod"),' >> $out
  echo '                            "data/Wpoly_mod.csv",' >> $out
  echo '                            { rollPeriod: 5,' >> $out
  echo '                              colors: ["blue", "red", "green", "black"],' >> $out
  echo '                              showRoller: true,' >> $out
  echo '                              yValueFormatter: function(x) {' >> $out
  echo '                                var shift = Math.pow(10, 4)' >> $out
  echo '                                return Math.round(x * shift) / shift' >> $out
  echo '                              },' >> $out
  echo '                            });' >> $out
  echo '          </script>' >> $out
  echo '        </td>' >> $out
  echo '      </tr>' >> $out
  echo '    </table>' >> $out
  echo '  </div>' >> $out
  echo '  <br><br>' >> $out

  echo '  <div style="width:880px; height:330px;">' >> $out
  echo '    <table>' >> $out
  echo '      <tr><th>g<sup>2</sup> from Wilson flow ('$tag')</th><th>Topological charge ('$tag')</th></tr>' >> $out
  echo '      <tr>' >> $out
  echo '        <td style="width:400px; height:300px;">' >> $out
  echo '          <div id="Wflow"></div>' >> $out
  echo '          <script type="text/javascript">' >> $out
  echo '            g = new Dygraph(document.getElementById("Wflow"),' >> $out
  echo '                            "data/Wflow.csv",' >> $out
  echo '                            { rollPeriod: 5,' >> $out
  echo '                              colors: ["blue", "red", "green", "black"],' >> $out
  echo '                              showRoller: true,' >> $out
  echo '                              yValueFormatter: function(x) {' >> $out
  echo '                                var shift = Math.pow(10, 4)' >> $out
  echo '                                return Math.round(x * shift) / shift' >> $out
  echo '                              },' >> $out
  echo '                            });' >> $out
  echo '          </script>' >> $out
  echo '        </td>' >> $out
  echo '        <td style="width:400px; height:300px;">' >> $out
  echo '          <div id="topo"></div>' >> $out
  echo '          <script type="text/javascript">' >> $out
  echo '            g = new Dygraph(document.getElementById("topo"),' >> $out
  echo '                            "data/topo.csv",' >> $out
  echo '                            { rollPeriod: 1,' >> $out
  echo '                              colors: ["blue", "red", "green", "black"],' >> $out
  echo '                              showRoller: true,' >> $out
  echo '                              yValueFormatter: function(x) {' >> $out
  echo '                                var shift = Math.pow(10, 3)' >> $out
  echo '                                return Math.round(x * shift) / shift' >> $out
  echo '                              },' >> $out
  echo '                            });' >> $out
  echo '          </script>' >> $out
  echo '        </td>' >> $out
  echo '      </tr>' >> $out
  echo '    </table>' >> $out
  echo '  </div>' >> $out
  echo '  <br><br>' >> $out

  echo '  <div style="width:880px; height:330px;">' >> $out
  echo '    <table>' >> $out
  echo '      <tr><th>Wilson flow anisotropy ('$tag')</th><th>Intentionally left blank</th></tr>' >> $out
  echo '      <tr>' >> $out
  echo '        <td style="width:400px; height:300px;">' >> $out
  echo '          <div id="Wflow_aniso"></div>' >> $out
  echo '          <script type="text/javascript">' >> $out
  echo '            g = new Dygraph(document.getElementById("Wflow_aniso"),' >> $out
  echo '                            "data/Wflow_aniso.csv",' >> $out
  echo '                            { rollPeriod: 5,' >> $out
  echo '                              colors: ["blue", "red", "green", "black"],' >> $out
  echo '                              showRoller: true,' >> $out
  echo '                              yValueFormatter: function(x) {' >> $out
  echo '                                var shift = Math.pow(10, 4)' >> $out
  echo '                                return Math.round(x * shift) / shift' >> $out
  echo '                              },' >> $out
  echo '                            });' >> $out
  echo '          </script>' >> $out
  echo '        </td>' >> $out
  echo '        <td style="width:400px; height:300px;">' >> $out
  echo '        </td>' >> $out
  echo '      </tr>' >> $out
  echo '    </table>' >> $out
  echo '  </div>' >> $out
  echo '  <br><br>' >> $out
fi

# Only include if we actually have something to show
if [ -f data/eig.csv ] ; then
  len=`wc -l data/eig.csv | awk '{print $1}'`
else
  len=0
fi
if [ $len -gt 1 ]; then
  echo '  <div style="width:880px; height:330px;">' >> $out
  echo '    <table>' >> $out
  echo '      <tr><th>Eigenvalues ('$tag')</th><th>Intentionally left blank</th></tr>' >> $out
  echo '      <tr>' >> $out
  echo '        <td style="width:400px; height:300px;">' >> $out
  echo '          <div id="eig"></div>' >> $out
  echo '          <script type="text/javascript">' >> $out
  echo '            g = new Dygraph(document.getElementById("eig"),' >> $out
  echo '                            "data/eig.csv",' >> $out
  echo '                            { rollPeriod: 5,' >> $out
  echo '                              colors: ["blue", "orange", "red", "green", "purple", "black"],' >> $out
  echo '                              showRoller: true,' >> $out
  echo '                              yValueFormatter: function(x) {' >> $out
  echo '                                var shift = Math.pow(10, 4)' >> $out
  echo '                                return Math.round(x * shift) / shift' >> $out
  echo '                              },' >> $out
  echo '                            });' >> $out
  echo '          </script>' >> $out
  echo '        </td>' >> $out
  echo '        <td style="width:400px; height:300px;">' >> $out
  echo '        </td>' >> $out
  echo '      </tr>' >> $out
  echo '    </table>' >> $out
  echo '  </div>' >> $out
  echo '  <br><br>' >> $out
fi
echo '  <br><br><p align="right"><a href="#top">Return to top</a></p>' >> $out

# Only include if we actually have something to show
if [ -f data/plaqB.csv ] ; then
  len=`wc -l data/plaqB.csv | awk '{print $1}'`
else
  len=0
fi
if [ $len -gt 1 ]; then
  echo '  <h1><a name="blocked"></a>Blocked observables</h1>' >> $out
  echo '  <hr><br>' >> $out
  echo '  <div style="width:880px; height:330px;">' >> $out
  echo '    <table>' >> $out
  echo '      <tr><th>Plaquette ('$tag')</th><th>Intentionally left blank</th></tr>' >> $out
  echo '      <tr>' >> $out
  echo '        <td style="width:400px; height:300px;">' >> $out
  echo '          <div id="plaqB"></div>' >> $out
  echo '          <script type="text/javascript">' >> $out
  echo '            g = new Dygraph(document.getElementById("plaqB"),' >> $out
  echo '                            "data/plaqB.csv",' >> $out
  echo '                            { rollPeriod: 5,' >> $out
  echo '                              colors: ["blue", "orange", "red", "green", "purple"],' >> $out
  echo '                              showRoller: true,' >> $out
  echo '                              yValueFormatter: function(x) {' >> $out
  echo '                                var shift = Math.pow(10, 4)' >> $out
  echo '                                return Math.round(x * shift) / shift' >> $out
  echo '                              },' >> $out
  echo '                            });' >> $out
  echo '          </script>' >> $out
  echo '        </td>' >> $out
  echo '        <td style="width:400px; height:300px;">' >> $out
  echo '        </td>' >> $out
  echo '      </tr>' >> $out
  echo '    </table>' >> $out
  echo '  </div>' >> $out
  echo '  <br><br>' >> $out

  echo '  <div style="width:880px; height:330px;">' >> $out
  echo '    <table>' >> $out
  echo '      <tr><th>Polyakov loop ('$tag')</th><th>Spatial loop ('$tag')</th></tr>' >> $out
  echo '      <tr>' >> $out
  echo '        <td style="width:400px; height:300px;">' >> $out
  echo '          <div id="polyB"></div>' >> $out
  echo '          <script type="text/javascript">' >> $out
  echo '            g = new Dygraph(document.getElementById("polyB"),' >> $out
  echo '                            "data/polyB.csv",' >> $out
  echo '                            { colors: ["blue", "orange", "red", "green", "purple"],' >> $out
  echo '                              drawPoints: true,' >> $out
  echo '                              strokeWidth: 0,' >> $out
  echo '                              showLabelsOnHighlight: false,' >> $out
  echo '                              xValueFormatter: function(x) {' >> $out
  echo '                                var shift = Math.pow(10, 4)' >> $out
  echo '                                return Math.round(x * shift) / shift' >> $out
  echo '                              },' >> $out
  echo '                              yValueFormatter: function(x) {' >> $out
  echo '                                var shift = Math.pow(10, 4)' >> $out
  echo '                                return Math.round(x * shift) / shift' >> $out
  echo '                              },' >> $out
  echo '                            });' >> $out
  echo '          </script>' >> $out
  echo '        </td>' >> $out
  echo '        <td style="width:400px; height:300px;">' >> $out
  echo '          <div id="xpolyB"></div>' >> $out
  echo '          <script type="text/javascript">' >> $out
  echo '            g = new Dygraph(document.getElementById("xpolyB"),' >> $out
  echo '                            "data/xpolyB.csv",' >> $out
  echo '                            { colors: ["blue", "orange", "red", "green", "purple"],' >> $out
  echo '                              drawPoints: true,' >> $out
  echo '                              strokeWidth: 0,' >> $out
  echo '                              showLabelsOnHighlight: false,' >> $out
  echo '                              xValueFormatter: function(x) {' >> $out
  echo '                                var shift = Math.pow(10, 4)' >> $out
  echo '                                return Math.round(x * shift) / shift' >> $out
  echo '                              },' >> $out
  echo '                              yValueFormatter: function(x) {' >> $out
  echo '                                var shift = Math.pow(10, 4)' >> $out
  echo '                                return Math.round(x * shift) / shift' >> $out
  echo '                              },' >> $out
  echo '                            });' >> $out
  echo '          </script>' >> $out
  echo '        </td>' >> $out
  echo '      </tr>' >> $out
  echo '    </table>' >> $out
  echo '  </div>' >> $out
  echo '  <br><br>' >> $out

  echo '  <div style="width:880px; height:330px;">' >> $out
  echo '    <table>' >> $out
  echo '      <tr><th>Re(Polyakov loop) ('$tag')</th><th>Polyakov loop mod ('$tag')</th></tr>' >> $out
  echo '      <tr>' >> $out
  echo '        <td style="width:400px; height:300px;">' >> $out
  echo '          <div id="poly_rB"></div>' >> $out
  echo '          <script type="text/javascript">' >> $out
  echo '            g = new Dygraph(document.getElementById("poly_rB"),' >> $out
  echo '                            "data/poly_rB.csv",' >> $out
  echo '                            { rollPeriod: 5,' >> $out
  echo '                              colors: ["blue", "orange", "red", "green", "purple"],' >> $out
  echo '                              showRoller: true,' >> $out
  echo '                              yValueFormatter: function(x) {' >> $out
  echo '                                var shift = Math.pow(10, 4)' >> $out
  echo '                                return Math.round(x * shift) / shift' >> $out
  echo '                              },' >> $out
  echo '                            });' >> $out
  echo '          </script>' >> $out
  echo '        </td>' >> $out
  echo '        <td style="width:400px; height:300px;">' >> $out
  echo '          <div id="poly_modB"></div>' >> $out
  echo '          <script type="text/javascript">' >> $out
  echo '            g = new Dygraph(document.getElementById("poly_modB"),' >> $out
  echo '                            "data/poly_modB.csv",' >> $out
  echo '                            { rollPeriod: 5,' >> $out
  echo '                              colors: ["blue", "orange", "red", "green", "purple"],' >> $out
  echo '                              showRoller: true,' >> $out
  echo '                              yValueFormatter: function(x) {' >> $out
  echo '                                var shift = Math.pow(10, 4)' >> $out
  echo '                                return Math.round(x * shift) / shift' >> $out
  echo '                              },' >> $out
  echo '                            });' >> $out
  echo '          </script>' >> $out
  echo '        </td>' >> $out
  echo '      </tr>' >> $out
  echo '    </table>' >> $out
  echo '  </div>' >> $out
  echo '  <br><br>' >> $out

  echo '  <div style="width:880px; height:330px;">' >> $out
  echo '    <table>' >> $out
  echo '      <tr><th>Re(spatial loop) ('$tag')</th><th>Spatial loop mod ('$tag')</th></tr>' >> $out
  echo '      <tr>' >> $out
  echo '        <td style="width:400px; height:300px;">' >> $out
  echo '          <div id="xpoly_rB"></div>' >> $out
  echo '          <script type="text/javascript">' >> $out
  echo '            g = new Dygraph(document.getElementById("xpoly_rB"),' >> $out
  echo '                            "data/xpoly_rB.csv",' >> $out
  echo '                            { rollPeriod: 5,' >> $out
  echo '                              colors: ["blue", "orange", "red", "green", "purple"],' >> $out
  echo '                              showRoller: true,' >> $out
  echo '                              yValueFormatter: function(x) {' >> $out
  echo '                                var shift = Math.pow(10, 4)' >> $out
  echo '                                return Math.round(x * shift) / shift' >> $out
  echo '                              },' >> $out
  echo '                            });' >> $out
  echo '          </script>' >> $out
  echo '        </td>' >> $out
  echo '        <td style="width:400px; height:300px;">' >> $out
  echo '          <div id="xpoly_modB"></div>' >> $out
  echo '          <script type="text/javascript">' >> $out
  echo '            g = new Dygraph(document.getElementById("xpoly_modB"),' >> $out
  echo '                            "data/xpoly_modB.csv",' >> $out
  echo '                            { rollPeriod: 5,' >> $out
  echo '                              colors: ["blue", "orange", "red", "green", "purple"],' >> $out
  echo '                              showRoller: true,' >> $out
  echo '                              yValueFormatter: function(x) {' >> $out
  echo '                                var shift = Math.pow(10, 4)' >> $out
  echo '                                return Math.round(x * shift) / shift' >> $out
  echo '                              },' >> $out
  echo '                            });' >> $out
  echo '          </script>' >> $out
  echo '        </td>' >> $out
  echo '      </tr>' >> $out
  echo '    </table>' >> $out
  echo '  </div>' >> $out
  echo '  <br><br>' >> $out
  echo '  <br><br><p align="right"><a href="#top">Return to top</a></p>' >> $out
fi

echo '  <h1><a name="evol"></a>Evolution observables</h1>' >> $out
echo '  <hr><br>' >> $out
echo '  <div style="width:880px; height:330px;">' >> $out
echo '    <table>' >> $out
echo '      <tr><th>HMC acceptance ('$tag')</th><th>exp(-delta S) ('$tag')</th></tr>' >> $out
echo '      <tr>' >> $out
echo '        <td style="width:400px; height:300px;">' >> $out
echo '          <div id="accP"></div>' >> $out
echo '          <script type="text/javascript">' >> $out
echo '            g = new Dygraph(document.getElementById("accP"),' >> $out
echo '                            "data/accP.csv",' >> $out
echo '                            { rollPeriod: 250,' >> $out
echo '                              colors: ["red"],' >> $out
echo '                              showRoller: true,' >> $out
echo '                              valueRange: [0, 1.01],' >> $out
echo '                              yValueFormatter: function(x) {' >> $out
echo '                                var shift = Math.pow(10, 3)' >> $out
echo '                                return Math.round(x * shift) / shift' >> $out
echo '                              },' >> $out
echo '                            });' >> $out
echo '          </script>' >> $out
echo '        </td>' >> $out
echo '        <td style="width:400px; height:300px;">' >> $out
echo '          <div id="exp_dS"></div>' >> $out
echo '          <script type="text/javascript">' >> $out
echo '            g = new Dygraph(document.getElementById("exp_dS"),' >> $out
echo '                            "data/exp_dS.csv",' >> $out
echo '                            { rollPeriod: 50,' >> $out
echo '                              colors: ["red"],' >> $out
echo '                              showRoller: true,' >> $out
echo '                              valueRange: [0, 2.01],' >> $out
echo '                              yValueFormatter: function(x) {' >> $out
echo '                                var shift = Math.pow(10, 4)' >> $out
echo '                                return Math.round(x * shift) / shift' >> $out
echo '                              },' >> $out
echo '                            });' >> $out
echo '          </script>' >> $out
echo '        </td>' >> $out
echo '      </tr>' >> $out
echo '    </table>' >> $out
echo '  </div>' >> $out
echo '  <br><br>' >> $out

echo '  <div style="width:880px; height:330px;">' >> $out
echo '    <table>' >> $out
echo '      <tr><th>delta S ('$tag')</th><th>|delta S| ('$tag')</th></tr>' >> $out
echo '      <tr>' >> $out
echo '        <td style="width:400px; height:300px;">' >> $out
echo '          <div id="deltaS"></div>' >> $out
echo '          <script type="text/javascript">' >> $out
echo '            g = new Dygraph(document.getElementById("deltaS"),' >> $out
echo '                            "data/deltaS.csv",' >> $out
echo '                            { rollPeriod: 5,' >> $out
echo '                              colors: ["red"],' >> $out
echo '                              showRoller: true,' >> $out
echo '                              valueRange: [-2.5, 2.51],' >> $out
echo '                              yValueFormatter: function(x) {' >> $out
echo '                                var shift = Math.pow(10, 4)' >> $out
echo '                                return Math.round(x * shift) / shift' >> $out
echo '                              },' >> $out
echo '                            });' >> $out
echo '          </script>' >> $out
echo '        </td>' >> $out
echo '        <td style="width:400px; height:300px;">' >> $out
echo '          <div id="abs_dS"></div>' >> $out
echo '          <script type="text/javascript">' >> $out
echo '            g = new Dygraph(document.getElementById("abs_dS"),' >> $out
echo '                            "data/abs_dS.csv",' >> $out
echo '                            { rollPeriod: 1,' >> $out
echo '                              colors: ["red"],' >> $out
echo '                              showRoller: true,' >> $out
echo '                              valueRange: [0, 5.01],' >> $out
echo '                              yValueFormatter: function(x) {' >> $out
echo '                                var shift = Math.pow(10, 4)' >> $out
echo '                                return Math.round(x * shift) / shift' >> $out
echo '                              },' >> $out
echo '                            });' >> $out
echo '          </script>' >> $out
echo '        </td>' >> $out
echo '      </tr>' >> $out
echo '    </table>' >> $out
echo '  </div>' >> $out
echo '  <br><br>' >> $out

echo '  <div style="width:880px; height:330px;">' >> $out
echo '    <table>' >> $out
echo '      <tr><th>Forces ('$tag')</th><th>CG iters per traj ('$tag')</th></tr>' >> $out
echo '        <td style="width:400px; height:300px;">' >> $out
echo '          <div id="force"></div>' >> $out
echo '          <script type="text/javascript">' >> $out
echo '            g = new Dygraph(document.getElementById("force"),' >> $out
echo '                            "data/force.csv",' >> $out
echo '                            { rollPeriod: 1,' >> $out
echo '                              colors: ["red", "blue", "green"],' >> $out
echo '                              showRoller: true,' >> $out
echo '                              yValueFormatter: function(x) {' >> $out
echo '                                var shift = Math.pow(10, 6)' >> $out
echo '                                return Math.round(x * shift) / shift' >> $out
echo '                              },' >> $out
echo '                            });' >> $out
echo '          </script>' >> $out
echo '        </td>' >> $out
echo '        <td style="width:400px; height:300px;">' >> $out
echo '          <div id="cg_iters"></div>' >> $out
echo '          <script type="text/javascript">' >> $out
echo '            g = new Dygraph(document.getElementById("cg_iters"),' >> $out
echo '                            "data/cg_iters.csv",' >> $out
echo '                            { rollPeriod: 1,' >> $out
echo '                              colors: ["red"],' >> $out
echo '                              showRoller: true,' >> $out
echo '                              yValueFormatter: function(x) {' >> $out
echo '                                var shift = Math.pow(10, 1)' >> $out
echo '                                return Math.round(x * shift) / shift' >> $out
echo '                              },' >> $out
echo '                            });' >> $out
echo '          </script>' >> $out
echo '        </td>' >> $out
echo '      </tr>' >> $out
echo '    </table>' >> $out
echo '  </div>' >> $out
echo '  <br><br>' >> $out

echo '  <div style="width:880px; height:330px;">' >> $out
echo '    <table>' >> $out
echo '      <tr><th>Wall-clock seconds per traj ('$tag')</th><th>Core-minutes per MDTU ('$tag')</th></th></tr>' >> $out
echo '      <tr>' >> $out
echo '        <td style="width:400px; height:300px;">' >> $out
echo '          <div id="walltime"></div>' >> $out
echo '          <script type="text/javascript">' >> $out
echo '            g = new Dygraph(document.getElementById("walltime"),' >> $out
echo '                            "data/walltime.csv",' >> $out
echo '                            { rollPeriod: 1,' >> $out
echo '                              colors: ["red"],' >> $out
echo '                              showRoller: true,' >> $out
echo '                              yValueFormatter: function(x) {' >> $out
echo '                                var shift = Math.pow(10, 1)' >> $out
echo '                                return Math.round(x * shift) / shift' >> $out
echo '                              },' >> $out
echo '                            });' >> $out
echo '          </script>' >> $out
echo '        </td>' >> $out
echo '        <td style="width:400px; height:300px;">' >> $out
echo '          <div id="wallTU"></div>' >> $out
echo '          <script type="text/javascript">' >> $out
echo '            g = new Dygraph(document.getElementById("wallTU"),' >> $out
echo '                            "data/wallTU.csv",' >> $out
echo '                            { rollPeriod: 1,' >> $out
echo '                              colors: ["red"],' >> $out
echo '                              showRoller: true,' >> $out
echo '                              yValueFormatter: function(x) {' >> $out
echo '                                var shift = Math.pow(10, 1)' >> $out
echo '                                return Math.round(x * shift) / shift' >> $out
echo '                              },' >> $out
echo '                            });' >> $out
echo '          </script>' >> $out
echo '        </td>' >> $out
echo '      </tr>' >> $out
echo '    </table>' >> $out
echo '  </div>' >> $out
echo '  <br><br><p align="right"><a href="#top">Return to top</a></p>' >> $out

echo '  <h1><a name="run"></a>Run parameters</h1>' >> $out
echo '  <hr><br>' >> $out
echo '  <div style="width:880px; height:330px;">' >> $out
echo '    <table>' >> $out
echo '      <tr><th>Steps per trajec ('$tag')</th><th>HMC step size ('$tag')</th></tr>' >> $out
echo '      <tr>' >> $out
echo '        <td style="width:400px; height:300px;">' >> $out
echo '          <div id="Nstep"></div>' >> $out
echo '          <script type="text/javascript">' >> $out
echo '            g = new Dygraph(document.getElementById("Nstep"),' >> $out
echo '                            "data/Nstep.csv",' >> $out
echo '                            { rollPeriod: 1,' >> $out
echo '                              colors: ["red", "blue", "green"],' >> $out
echo '                              showRoller: true,' >> $out
echo '                              yValueFormatter: function(x) {' >> $out
echo '                                var shift = Math.pow(10, 1)' >> $out
echo '                                return Math.round(x * shift) / shift' >> $out
echo '                              },' >> $out
echo '                            });' >> $out
echo '          </script>' >> $out
echo '        </td>' >> $out
echo '        <td style="width:400px; height:300px;">' >> $out
echo '          <div id="stepsize"></div>' >> $out
echo '          <script type="text/javascript">' >> $out
echo '            g = new Dygraph(document.getElementById("stepsize"),' >> $out
echo '                            "data/stepsize.csv",' >> $out
echo '                            { rollPeriod: 1,' >> $out
echo '                              colors: ["red", "blue", "green"],' >> $out
echo '                              showRoller: true,' >> $out
echo '                              yValueFormatter: function(x) {' >> $out
echo '                                var shift = Math.pow(10, 5)' >> $out
echo '                                return Math.round(x * shift) / shift' >> $out
echo '                              },' >> $out
echo '                            });' >> $out
echo '          </script>' >> $out
echo '        </td>' >> $out
echo '      </tr>' >> $out
echo '    </table>' >> $out
echo '  </div>' >> $out
echo '  <br><br>' >> $out

echo '  <div style="width:880px; height:330px;">' >> $out
echo '    <table>' >> $out
echo '      <tr><th>Hasenbusch mass ('$tag')</th><th>Trajectory length ('$tag')</th></tr>' >> $out
echo '      <tr>' >> $out
echo '        <td style="width:400px; height:300px;">' >> $out
echo '          <div id="MH"></div>' >> $out
echo '          <script type="text/javascript">' >> $out
echo '            g = new Dygraph(document.getElementById("MH"),' >> $out
echo '                            "data/MH.csv",' >> $out
echo '                            { rollPeriod: 1,' >> $out
echo '                              colors: ["green"],' >> $out
echo '                              showRoller: true,' >> $out
echo '                              yValueFormatter: function(x) {' >> $out
echo '                                var shift = Math.pow(10, 3)' >> $out
echo '                                return Math.round(x * shift) / shift' >> $out
echo '                              },' >> $out
echo '                            });' >> $out
echo '          </script>' >> $out
echo '        </td>' >> $out
echo '        <td style="width:400px; height:300px;">' >> $out
echo '          <div id="tlength"></div>' >> $out
echo '          <script type="text/javascript">' >> $out
echo '            g = new Dygraph(document.getElementById("tlength"),' >> $out
echo '                            "data/tlength.csv",' >> $out
echo '                            { rollPeriod: 1,' >> $out
echo '                              colors: ["green"],' >> $out
echo '                              showRoller: true,' >> $out
echo '                              yValueFormatter: function(x) {' >> $out
echo '                                var shift = Math.pow(10, 3)' >> $out
echo '                                return Math.round(x * shift) / shift' >> $out
echo '                              },' >> $out
echo '                            });' >> $out
echo '          </script>' >> $out
echo '        </td>' >> $out
echo '      </tr>' >> $out
echo '    </table>' >> $out
echo '  </div>' >> $out
echo '  <br><br><p align="right"><a href="#top">Return to top</a></p>' >> $out
echo '</div>' >> $out
echo '</body>' >> $out
echo '</html>' >> $out
